# see: https://github.com/game-ci/unity-builder
name: Unity Builder
description: "Build Unity projects for different platforms."
inputs:
  targetPlatform:
    required: true
    default: ""
    description: "Platform that the build should target."
  unityVersion:
    required: false
    default: "auto"
    description: 'Version of unity to use for building the project. Use "auto" to get from your ProjectSettings/ProjectVersion.txt'
  projectPath:
    required: true
    default: ""
    description: "Relative path to the project to be built."
  buildMethod:
    required: true
    default: ""
    description: "Path to a Namespace.Class.StaticMethod to run to perform the build."
  customParameters:
    required: false
    default: ""
    description: "Custom parameters to configure the build."
  versioning:
    required: false
    default: "None"
    description: "The versioning scheme to use when building the project"

runs:
  using: "composite"
  steps:
    - name: Replace last 4 charactors of UNITY_SERIAL and mask it.
      shell: bash
      run: echo "::add-mask::$(echo ${{ env.UNITY_SERIAL }} | sed 's/....$//')XXXX"
    # see: https://github.com/game-ci/unity-builder
    # see: https://game.ci/docs/github/builder/
    - name: Build Unity
      uses: game-ci/unity-builder@v2
      with:
        targetPlatform: ${{ inputs.targetPlatform }}
        unityVersion: ${{ inputs.unityVersion }}
        projectPath: ${{ inputs.projectPath }}
        buildMethod: ${{ inputs.buildMethod }}
        customParameters: ${{ inputs.customParameters }}
        versioning: ${{ inputs.versioning }}
