# use by...
# $ ghalint run
# $ ghalint --config ../Actions/.pinact.yaml run
excludes:
  # forked action/checkout on Cysharp/Actions repository
  - policy_name: checkout_persist_credentials_should_be_false
    action_file_path: .github/actions/checkout/action.yaml
  # action_ref_should_be_full_length_commit_sha, allow repository use Cysharp/Actions as tag.
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: Cysharp/Actions/.github/actions/*
  - policy_name: action_ref_should_be_full_length_commit_sha
    action_name: Cysharp/Actions/.github/workflows/*
  # deny_inherit_secrets, allow repository pass secrets to Cysharp/Actions create-release and toc-generator
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/test-create-release.yaml
    job_name: create-release
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/test-create-release.yaml
    job_name: create-release2
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/test-create-release.yaml
    job_name: create-release3
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/build-release.yaml
    job_name: create-release
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/release.yaml
    job_name: create-release
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/toc.yaml
    job_name: toc
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/benchmark.yaml
    job_name: loader
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/benchmark.yaml
    job_name: benchmark
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/benchmark.yaml
    job_name: cleanup-failed
  - policy_name: deny_inherit_secrets
    workflow_file_path: .github/workflows/pr-merged.yaml
    job_name: post
