name: Test setup-dotnet

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - uses: ./.github/actions/setup-dotnet
      - name: Test
        run: |
          dotnet --list-sdks | grep "6.0"
          dotnet --list-sdks | grep "7.0"
          dotnet --list-sdks | grep "8.0"
          dotnet --list-sdks | grep "9.0"
          dotnet --list-sdks | grep "10.0"
