name: actionlint cysharp

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * WED" # every wednesday 10:00 +9(JST)

jobs:
  pre:
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    outputs:
      repositories: ${{ steps.list.outputs.repositories }}
    steps:
      - name: List non-archived OSS Repository names, and pass to matrix
        id: list
        run: echo "names=$(gh repo list Cysharp --visibility public --no-archived --json name --jq "sort_by(.name | ascii_downcase) | .[] | .name" --limit 100)" | tee -a "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  actionlint:
    needs: [pre]
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJson(needs.pre.outputs.repositories) }}
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.43.1
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          repository: "cysharp/${{ matrix.repository }}"
          path: ${{ matrix.repository }}
      # github workflows/action's Static Checker
      - name: Run actionlint
        run: actionlint -color -oneline --config-file ../.github/actionlint.yaml
        working-directory: ${{ matrix.repository }}
      # checkout's persist-credentials: false checker
      - name: Run ghalint
        run: ghalint -c ../.ghalint.yaml run
        working-directory: ${{ matrix.repository }}
      - name: Run ghalint
        run: ghalint -c ../.ghalint.yaml run-action
        working-directory: ${{ matrix.repository }}
