name: Prevent github change
on:
  workflow_call:
  pull_request:
    branches: ["main"]
    paths:
      - ".github/**/*.yaml"
      - ".github/**/*.yml"

# prevent fork user to change
jobs:
  detect:
    # detect if PR is from fork, but allow dependabot PR.
    if: ${{ github.event.pull_request.head.repo.fork && github.triggering_actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: "Prevent file change"
        run: exit 1
