name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: true

on:
  workflow_dispatch: null

jobs:
  build:
    permissions:
      contents: write
      actions: read
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          persist-credentials: false
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: 9.0.x
      - name: dotnet publish (x64)
        run: dotnet publish ./src/CysharpActions -c Release --runtime linux-x64 -o ./actions/Linux-X64
      - name: dotnet publish (arm64)
        run: dotnet publish ./src/CysharpActions -c Release --runtime linux-arm64 -o ./actions/Linux-ARM64
      - name: list files
        run: ls -lR ./actions/
      - name: Check update on git
        id: check_update
        run: git diff --exit-code || echo "changed=1" | tee -a "$GITHUB_OUTPUT"
      - name: Commit files (updated? = ${{ steps.check_update.outputs.changed == '1' }})
        id: update
        run: |
          if [[ "${{ steps.check_update.outputs.changed }}" == "1" ]]; then
            git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${{ github.repository }}"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add -A
            git commit -m "[automate] New CysharpActions.exe commited" -m "Commit by [GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" -a
            echo "commited=1" | tee -a "$GITHUB_OUTPUT"
          else
            echo "commited=0" | tee -a "$GITHUB_OUTPUT"
          fi
      - name: Push changes
        if: ${{ steps.update.outputs.commited == '1' }}
        uses: ad-m/github-push-action@d91a481090679876dfc4178fef17f286781251df
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # auto generated token
          branch: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
          tags: false
