name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-release
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: 9.0.x
      - name: dotnet publish
        run: dotnet publish ./src/CysharpActions -c Release -o ./actions/

      - name: Check update on git
        id: check_update
        run: git diff --exit-code || echo "changed=1" | tee -a "$GITHUB_OUTPUT"
      - name: Commit files (updated? = ${{ steps.check_update.outputs.changed == '1' }})
        id: commit
        run: |
          if [[ "${{ steps.check_update.outputs.changed }}" == "1" ]]; then
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "feat: Update package.json to ${{ needs.validate.outputs.normalized_tag }}" -m "Commit by [GitHub Actions](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})" -a
            echo "sha=$(git rev-parse HEAD)" | tee -a "$GITHUB_OUTPUT"
            echo "is-branch-created=${{ inputs.dry-run }}" | tee -a "$GITHUB_OUTPUT"
          elif [[ "${{ inputs.ref }}" != "" ]]; then
            echo "sha=$(git rev-parse HEAD)" | tee -a "$GITHUB_OUTPUT"
            echo "is-branch-created=false" | tee -a "$GITHUB_OUTPUT"
          else
            echo "sha=" | tee -a "$GITHUB_OUTPUT"
            echo "is-branch-created=false" | tee -a "$GITHUB_OUTPUT"
          fi
      - name: Push changes
        if: ${{ steps.update.outputs.commited == '1' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # auto generated token
          branch: ${{ steps.update.outputs.branch-name || inputs.ref }}
          tags: false
          force: ${{ inputs.dry-run }}
