name: Test Actions

on:
  pull_request:
    branches: ["main"]

env:
  GH_REPO: ${{ github.repository }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  setup-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: 9.0.x
      - name: dotnet build
        run: dotnet build -c Release
      - name: dotnet test
        run: dotnet test -c Release --no-build --logger:"console;verbosity=normal"

  upload-artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: Cysharp/Actions/.github/actions/upload-artifact@main
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

  download-artifact:
    needs: [upload-artifact]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/download-artifact@main
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R
