name: Test checkout

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - name: Test
        run: |
          if [[ -f "README.md" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
          if [[ -d ".github" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
          if [[ -f ".github/actions/checkout/action.yaml" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
          if [[ -f ".github/workflows/create-release.yaml" ]]: then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
          if [[ -d "src" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
