name: Test Actions

on:
  pull_request:
    branches: ["main"]

env:
  GH_REPO: ${{ github.repository }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: 9.0.x
      - name: dotnet build
        run: dotnet build -c Release
      - name: dotnet test
        run: dotnet test
