name: Test check-benchmarkable

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-benchmarkable
        id: check-benchmarkable
        with:
          username: foo
      - uses: ./.github/actions/check-benchmarkable
        id: check-benchmarkable2
        with:
          username: mayuki
      - name: Test
        run: |
          echo "DEBUG: check-metas: ${{ steps.check-benchmarkable.outputs.authorized }}"

          echo -n "FACT: foo is not allowed. "
          if [[ "${{ steps.check-benchmarkable.outputs.authorized }}" != "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
          echo -n "FACT: mayuki is allowed. "
          if [[ "${{ steps.check-benchmarkable2.outputs.authorized }}" == "true" ]]; then echo "[O PASS]"; else echo "[X FAIL]" && exit 1; fi
