name: TOC Generator

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  toc:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/toc-generator@9e238e7974de5fcf7b17b7acc54c896160dda0a3 # v4.3.1
        with:
          TOC_TITLE: "# 📖 Table of Contents"
          FOLDING: false
