name: (R) Validate Tag

on:
  workflow_call:
    inputs:
      require-validation:
        description: "require-validation: true disallow old tag or any invalid tag. false keep going even validate failed."
        required: false
        default: false
        type: boolean
      tag:
        description: "tag: tag to validate"
        required: true
        type: string
    outputs:
      normalized-tag:
        description: normalized tag, tag without v prefix.
        value: ${{ jobs.validate.outputs.normalized-tag }}
      tag:
        description: same as input tag
        value: ${{ jobs.validate.outputs.tag }}
      validated:
        description: result of the validation is validated or not
        value: ${{ jobs.validate.outputs.validated }}
  workflow_dispatch:
    inputs:
      require-validation:
        description: "require-validation: allow old tag or not"
        required: false
        default: false
        type: boolean
      tag:
        description: "tag: tag to validate"
        required: true
        type: string

permissions:
  contents: read
  actions: read

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      normalized-tag: ${{ steps.validate.outputs.normalized-tag }}
      tag: ${{ steps.validate.outputs.tag }}
      validated: ${{ steps.validate.outputs.validated }}
    steps:
      - uses: actions/checkout@v4
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - name: Validate Tag
        id: validate
        run: dotnet run --project "./src/Actions/Actions.csproj" -- validate-tag --tag "${{ inputs.tag }}" ${{ inputs.require-validation && '--require-validation' || '' }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
